import Head from "next/head";
import Image from "next/image";
import React, { useRef, Component, useState } from "react";
import { Inter } from "@next/font/google";
import Talk from "../components/talkElement/talk";
import Send from "../components/talkElement/Send";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });

type Talk = {
  name1: string;
  name2: string;
  content: string;
};

export default function Message() {
  const [talk_list, setTalkList] = useState<Talk[]>([]);

  const button_send = (mesText: string, user: string) => {
    console.log(mesText);
    console.log(user);
    // 入力チェック
    if (mesText === "") return;

    if (user == "sam") {
      setTalkList([
        ...talk_list,
        {
          name1: "andy_talk",
          name2: "andy_box",
          content: mesText,
        },
      ]);
    } else {
      setTalkList([
        ...talk_list,
        {
          name1: "sam_talk",
          name2: "sam_box",
          content: mesText,
        },
      ]);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          id="talk-room"
          style={{
            width: "100%",
            height: "780px",
            overflow: "scroll",
            background: "url(/talk.png)",
          }}
        >
          {talk_list.map((talk, index) => (
            <Talk key={index} name1={talk.name1} name2={talk.name2}>
              {talk.content}
            </Talk>
          ))}
        </div>
        <div id="text-area">
          <Send
            button_send={(event, user) =>
              button_send(event as string, user as string)
            }
          ></Send>
        </div>
      </main>
    </>
  );
}
