import Head from 'next/head'
import { useState } from 'react';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { finished } from 'stream';
import BasicTemplate from "../components/Templates/BasicTemplate"
const inter = Inter({ subsets: ['latin'] })

export default function Todo() {
    // useState:状態のおまじない
    //リスト 　todoは変数、setTodoは関数todoを変更するときに使う
    // string


    const [todo, setTodo] = useState<string[]>(
        ["不動産案件の学生を集める",
            "先輩の論文を読む",
            "ボロノイの勉強をする"]
    );
    // テキストを格納するための変数
    const [inputItem, setInputItem] = useState<string>("");
    // リストの削除
    const finishedItem = (item: String) => {
        const newTodo = todo.filter(todo => todo != item);
        setTodo(newTodo);
    };
    // リストの追加
    const insertTodo = () => {
        // ===←型まで比較する
        if (inputItem === "") return;
        // 上書きしてない　concat追加
        const newTodo = todo.concat(inputItem);
        setTodo(newTodo);
        setInputItem("");
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BasicTemplate>
                <main className={styles.main}>
                    <h1>todoリスト</h1>
                    <div>
                        <input type="text" placeholder='ToDoを追加'
                            onChange={(event) => setInputItem(event.target.value)}
                            value={inputItem}
                        />
                        <button onClick={() => insertTodo()}>追加</button>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th>TODO</th>
                                <th>完了</th>
                            </tr>
                        </thead>
                        <tbody>
                            {todo.map((item) => {
                                return (
                                    <tr key={item}>
                                        <td>{item}</td>
                                        <td>
                                            <button onClick={() => finishedItem(item)}>完了</button>
                                        </td>
                                    </tr>
                                )
                            })}
                        </tbody>
                    </table>
                </main>
            </BasicTemplate>
        </>
    )
}
